trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp -r * $(Build.ArtifactStagingDirectory)
  displayName: 'Copy static files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'